next.config.mjs
src/app/(popup)/popup/page.tsx
src/app/cardslide/page.tsx
src/components/CardSlider.tsx
src/containers/layout/Sidebar.tsx
src/containers/popup/LoginPopup.tsx

- vercel 배포 연결을 해보기 위해서 npm run build 시 나오는 warnning 해결
- 상세 사항은 issue 에 참고
<br/>
- 위와 같은 이유로 Sidebar.tsx 를 이렇게 변경했는데 괜찮을까요?!
> 버그 
> *  `Unhandled Runtime Error
> Error: Image with src "/icon/home_plain.svg" is missing required "width" property.`
> 
> 해결
> * `Sidebar.tsx` , `/app/cardslide/page.tsx`
> ```
> export default function Sidebar() {
>   // Image 의 필수 요소 때문에 width, height 를 지정해 주었지만, 영향을 미치지 않습니다.
>   const size = 300;
>   return (
>     <section className={styles.container}>
>       <div></div>
>       <button className={styles.button}>
>         <Image
>           src="/icon/home_plain.svg"
>           alt="Home Icon"
>           className={styles.icon}
>           width={size}
>           height={size}
>         />
> ```
> 
> _Originally posted by @jwo1024 in …

Fix/fix warnning #10

---

.vscode/settings.json
src/app/(default)/collection/page.tsx
src/components/SearchPage.tsx
src/components/SubTopper.tsx
src/containers/layout/Maincontent.tsx
src/containers/map/Map.tsx
src/containers/overlay/Overlay.tsx
src/redux/locationSlice.tsx
src/redux/store.tsx
src/styles/components/_subtopper.module.scss
src/styles/layout/_collectionPage.module.scss
src/utils/GeoCoding.tsx

-  redux 적용 및 추가(locationSlice)
- 지도에서 현재 내 위치로 이동 + 레이아웃에 표기 추가
- 지도에서 드래그로 이동시 현재 보고있는 지도상 주소 표기 추가
- 지도 재생성 시 위에 덧씌워지는 방식에서 기존것 없에고 새롭게 생성되도록 변경
<br/>
-  노션에 있는 key 3개 env에 넣어야합니닷
<br/>
- #16 
- 
<br/>
<br/>

Feature/ redux 추가, 내위치, 지도로 보고있는 위치 주소 표기 추가 #16

---

src/app/(default)/collection/edit/page.tsx
src/components/LoginAccount.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/layout/Sidebar.tsx
src/styles/layout/_collectionEditPage.module.scss
src/styles/layout/_maincontent.module.scss
src/styles/layout/_profileEditPage.module.scss

- 로그인 계정별 버튼부분 p 태그 내부에 div 태그로 인한 오류발생 수정
- maincontent에서 스크롤바 안보이도록 수정 (임시)
- collection edit페이지 구현
<br/>
- collection edit 페이지에서 태그 입력 후 엔터누르면 태그 추가 가능, 띄어쓰기 불가 및 5글자 제한
- 이미 존재하는 태그 한번 더 입력, 클릭 시 태그 삭제
<br/>
- #33
<br/>
-
<br/>

Fix: setting페이지 로그인 계정버튼 표시 부분 오류 수정, maincontent 스크롤바 안보이도록 수정, collection edit페이지 구현

---

src/app/(default)/loading.tsx
src/app/api/collections/[collection_id]/dummydata.json
src/app/api/collections/[collection_id]/pins/route.tsx
src/app/api/search/place/dummydata.json
src/components/PinCard.tsx
src/components/PlaceCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/layout/SubPageLayout.tsx
src/containers/pin/PinSelectPage.tsx
src/styles/components/_pincard.module.scss
src/styles/containers/collection/_collectionEditPage.module.scss
src/styles/containers/pin/_pinSelectPage.module.scss
src/styles/layout/_subPageLayout.module.scss

- SubPageLayout에 scrollTop, 완료버튼 추가
- PinSelectPage api 연결 준비
- pinSelectPage 에 쿼리 넣어야 정상작동하도록 수정 
- `/pin/select?collectionId=${collectionId}`
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

Feat/edit pages #46

---

public/dummy-data/dummy-pin.json
src/app/api/places/[place_id]/dummydata.json
src/components/CardSlider2.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/login/LoginPage.tsx
src/containers/overlay/Overlay.tsx
src/containers/pin/PinSelectPage.tsx
src/containers/place/PlacePage.tsx
src/containers/profile/ProfilePage.tsx
src/containers/search/SearchPage.tsx
src/styles/base/_placeholders.scss
src/styles/components/_cardslider2.module.scss
src/styles/components/_collectioncard.module.scss
src/styles/components/_pincard.module.scss
src/styles/components/_placecard.module.scss
src/styles/containers/overlay/_overlay.module.scss
src/styles/containers/pin/_pinSelectPage.module.scss
src/styles/containers/search/_searchPage.module.scss
src/types/Profile.tsx

- overlay
-  pincard, placecard grid 수정
-  cardslider 넘어갈때 애니메이션 추가
- search page
-  fetch 실패시 메시지 출력
- input에 clear button 추가
- dummydata 내용 수정
- type 수정
- ProfileMine의 userId -> id
- login 페이지 
- profile 정보 localstorage 에 저장
<br/>
- 
- 
<br/>
- #59 
- 
<br/>
-
<br/>

Refact/overlay cardslider2 #59

---

src/containers/popup/LoginPopup.tsx

- 부모 window 에서 popup창의 메시지를 받지 못하는 문제
-  loginPopup 에서 부모 window에게 메시지 보내는 부분을 비동기적으로 수행되도록 수정하였습니다.
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

fix: loginPopup 비동기 수정

---

src/containers/popup/LoginPopup.tsx

- popup page , await 키워드 누락
- 
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

fix: await 누락

---

src/containers/map/newMap.tsx

- 마커 목록 클릭해서 페이지이동
- 드래그, 줌 시 제자리로 돌아오던 오류
- 메인창이 켜진채로 마커 불러와질 시 약간 오른쪽으로 치우쳐서 지도 보여줌
<br/>
- 
<br/>
- #43 
<br/>
-
<br/>

Feat/naver map marker #43

---

src/containers/login/LoginPage.tsx
src/containers/popup/LoginPopup.tsx
src/styles/containers/login/_login.module.scss

- popup 연결 수정
- login 페이지 message 주고 받는 부분이 실행이 안됨
- 로그인 errorMessage 추가
- localstorage 에 `myProfile` 으로 로그인 내용 저장하도록 만들었습니다.
\
<br/>
- 배포 올려서, 백엔드와의 연결 잘 동작하는지 확인해보고 #63에 정상작동 하는지 코멘트 달아두겠습니닷
<br/>
-
- 
<br/>
-
<br/>

fix: login popup 연결 수정

---

src/containers/layout/Sidebar.tsx
src/containers/map/newMap.tsx
src/containers/overlay/Overlay.tsx
src/containers/profile/ProfileBookmarkRenderer.tsx
src/styles/containers/overlay/_overlay.module.scss

- 오버레이의 컬렉션 선택버튼 클릭시 하이라이트되도록 변경
- 프로필의 찜 목록 보기 버튼 수정
<br/>
<br/>
<br/>
<br/>

오버레이, 프로필페이지 관련 자잘한 수정사항

---

src/containers/login/LoginPage.tsx

- login test log 추가
- 
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

test: login test log 추가

---

src/containers/login/LoginPage.tsx

- fetch hearer 에 credentials 추가 (테스트 해봐야함)
- 
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

fix: crecredentials 추가

---

src/containers/map/newMap.tsx

- 오버레이 컬렉션 선택 해제 후 마커배열을 초기화해주지 않아 생기던 문제를 해결했습니다
<br/>
-
- 
<br/>
- #79 
- 
<br/>
-
<br/>

fix: 오버레이 컬렉션 선택 해제 후 지도 이동시 오류 해결 #79

---

src/utils/fetchGetAvatarPresignedUrl.tsx

- api endpoint 오타 수정
- 
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

fix: api endpoint 오타 수정

---

src/utils/fetchDeleteCollectionLikes.tsx
src/utils/fetchDeleteCollectionScraps.tsx
src/utils/fetchDeleteFollow.tsx
src/utils/fetchGetAvatarPresignedUrl.tsx
src/utils/fetchPostCollectionLikes.tsx
src/utils/fetchPostCollectionScraps.tsx
src/utils/fetchPostFollow.tsx

- fetch api 잘못된 경로 수정
- 
<br/>
- 
- 
<br/>
- #83 
- 
<br/>
-
<br/>

fix: api 경로 수정

---

next.config.mjs
src/app/(default)/collection/edit/[id]/page.tsx
src/components/PlaceCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/collection/CollectionInfoRenderer.tsx
src/containers/collection/CollectionReplyRenderer.tsx
src/containers/collection/CollectionSelectPage.tsx
src/containers/profile/ProfileEditPage.tsx
src/containers/profile/ProfileInfoRenderer.tsx
src/styles/components/_alertModal.module.scss
src/styles/containers/collection/_collectionPage.module.scss
src/types/PresingedUrl.tsx
src/utils/checkLogin.tsx
src/utils/fetchGetAvatarPresignedUrl.tsx
src/utils/fetchGetCollectionPresignedUrl.tsx
src/utils/fetchPostCollection.tsx
src/utils/fetchPostPin.tsx
src/utils/fetchPutCollection.tsx
src/utils/fetchPutS3PresingedUrl.tsx

- 프로필 edit 페이지 수정
- collection 생성 / 수정 기능
- pin 리스트는 아직 동작안함
- presigned url 관련 fetch 보수
<br/>
- 
- 
<br/>
- #83 
- #85 
<br/>
-
<br/>

Feat/collection page #85

---

src/containers/layout/Sidebar.tsx
src/containers/map/Map.tsx
src/containers/overlay/Overlay.tsx
src/styles/layout/_sidebar.module.scss

- 사이드바 로그인 안 한 상태에서 표시 아이콘 변경
- infowindow 닫아주는 이벤트 추가
<br/>
- 
- 
<br/>
- #43 
- #91 
<br/>
-
<br/>

Fix/sidebar login, map event #43 #91

---

src/components/PinCard.tsx
src/containers/layout/Sidebar.tsx
src/containers/main/MainPage.tsx
src/containers/overlay/Overlay.tsx
src/containers/overlay/OverlayTopper.tsx

- pinCard의 지도에서보기 추가
- api 호출부 credential 빠져서 오류나는 부분 수정
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

Fix/api credential 빠진부분 추가, pincard의 지도에서보기 추가

---

src/utils/fetchPostCollection.tsx

- presignedurl 있는 응답, presingedurl 없는 응답 조건문 수정
<br/>
<br/>
<br/>
<br/>

fix: presignedurl 있는 응답, presingedurl 없는 응답 조건문 수정

---

src/components/PinCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/collection/CollectionPage.tsx
src/containers/collection/CollectionReplyInput.tsx
src/containers/collection/CollectionReplyRenderer.tsx
src/containers/layout/Sidebar.tsx
src/containers/profile/ProfileCollectionsRenderer.tsx
src/styles/containers/collection/_collectionInfo.module.scss
src/types/Pin.tsx

- 자잘한 오류들을 수정하였습니다...
- collection 생성시 이미지 안올라가는 문제
[fix: collection 생성시 잘못된 이미지 url 올리고 있는 부분 수정](https://github.com/PinTogether/frontend/commit/38930c2208c90153d4ad2d33876c4d4b2f00fc86)
- 로그인시 sidebar 의 프로필이미지 업데이트 되지 않는 문제
[fix: 로그인 시 myProfile 변경되면서 sidebar 의 profile 도 업데이트](https://github.com/PinTogether/frontend/commit/2b9f4cd9d79994ddcb56523f7512461ae3a1072c)
- pinCard 의 edit icon 라우팅 경로 수정
[fix: pin edit 페이지 라우팅 경로 수정](https://github.com/PinTogether/frontend/commit/b6ec566325589a58f7b1fb5259594f34c433150a)
- 컬렉션 infinity scroll 끝에 다달으면 존재하던 컬렉션 리스트가 보이지 않고 "컬렉션이 없습니다" 출력되는 문제 수정
[fix: collection 렌더 조건 수정](https://github.com/PinTogether/frontend/commit/39ae596415ff1bd04e35138ba4d963ef1e437945)
- collection page 좋아요 클릭시 레이아웃 움찔 흔들림 고정
[desgin: 좋아요 클릭시 레이아웃 움직이는 것 고정 (flex -> …

Fix 자잘한 오류 수정

---

src/containers/layout/Sidebar.tsx
src/containers/overlay/Overlay.tsx

- 컬렉션 핀 불러오는 api에 컬렉션 id를 잘못 넣고있어서 404 오류만 나오던것 수정했습니다
- 겸사겸사 더미데이터도 없엤습니다
<br/>
- 
- 
<br/>
-
- 
<br/>
-
<br/>

fix: 오버레이 컬렉션 더미데이터 삭제 및 핀 불러오는 api 잘못 들어가고 있던 값 수정

---

src/components/PinCard.tsx
src/components/PlaceCard.tsx
src/containers/main/MainPage.tsx
src/containers/map/Map.tsx
src/containers/profile/ProfileStarredRenderer.tsx
src/styles/containers/main/_mainPage.module.scss
src/utils/makeMarker.tsx

- 메인페이지 검색창 사용 가능
- 메인페이지 카드 슬라이더 길이 맞춰서 나오도록 수정 (임시)
- placecard, pincard에서 마커 띄울때 마커 아이콘 이상하게 보이던것 핀 수 무조건 0으로 나오던 것 수정
- 프로필 찜목록 선택에서 클릭이 아닌 터치도 가능하도록 추가
<br/>
- 메인페이지에 띄워지는 추천목록에 저희 4명꺼 추천으로 넣으면 어떨까요 일단 어떨까 볼겸 두명만 추가해놓긴 했는데 별로면 바로 빼도됩니닷
<br/>
- #116 
<br/>
-
<br/>

Feat/메인페이지, 마커, 프로필 찜 보기 수정

---

src/components/CollectionCard.tsx
src/components/GlobalAlertModal.tsx
src/components/PlaceCard.tsx
src/components/ReviewCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/collection/CollectionInfoRenderer.tsx
src/containers/pin/PinEditPage.tsx
src/containers/profile/ProfileEditPage.tsx
src/containers/profile/ProfileMyInfoPage.tsx
src/containers/profile/ProfileSettingPage.tsx
src/containers/profile/ProfileStarredRenderer.tsx
src/hooks/useLogout.tsx
src/styles/components/_placecard.module.scss
src/types/Place.tsx
src/utils/fetchGetPlacePins.tsx
src/utils/fetchGetStars.tsx
src/utils/fetchPostCollectionPresignedUrl.tsx
src/utils/fetchPostPin.tsx

Fix/  #114
* [fix: 수정페이지 입장시 현재 프로필로 세팅해두기](https://github.com/PinTogether/frontend/commit/69dc6290a556a683b7d411550452d5a37894f6e5) 
* [fix: endpint 오타 수정](https://github.com/PinTogether/frontend/commit/4c846fbb53bda8e52df8c9151859442b5cd8014f) 
* [feat: placeCard title 클릭시 PlacePage 로 이동](https://github.com/PinTogether/frontend/commit/6c3e960593fb40578d5b886d3c12db06e91bbb62) 
* [feat: ReviewCard 컬렉션 보러가기 클릭시 컬렉션 페이지로 이동](https://github.com/PinTogether/frontend/commit/401e853a2751b815137f7f729ba521ddb2070c58) 
* [fix: fetch 메소드에 맞게 컴포넌트명 변경](https://github.com/PinTogether/frontend/commit/7107d22fbd71b8c2aab3c2e49e2e462723c47bf6)
* [fix&refact: pin edit page](https://github.com/PinTogether/frontend/commit/9e7431ea7582f14c3c775f8410a021ddf08c091e) 
* [refactor&feat: logout 로직 hook 으로 분리, …

Feat/ 찜 목록 삭제 & Fix/  #114

---

src/app/(default)/collection/[id]/page.tsx
src/components/InputComponent.tsx
src/components/SlideMenu.tsx
src/containers/profile/ProfileEditPage.tsx
src/containers/profile/ProfileInfoRenderer.tsx
src/containers/profile/ProfileStarredRenderer.tsx
src/containers/search/SearchPage.tsx
src/styles/containers/profile/_profileEditPage.module.scss
src/styles/containers/profile/_profilePage.module.scss
src/styles/layout/_editPageLayout.module.scss
src/utils/members/fetchGetMemberNameValid.tsx
src/utils/members/fetchPutMyProfile.tsx

- 프로필 페이지
- 프로필 사용자 이름(memebername), 소개(bio) 추가
- 프로필 수정 페이지
-  EditPageLayout gap 줄임, sectionTitle내 icon 색상 변경
- memebername 자동 유효 검사 추가
-  프로필 수정 api , request body 속성 추가된 것 추가 및 수정 (name, membername, bio)
- 검색 페이지
- searchPage slidemenu 선택된 메뉴 쿼리스트링이랑 연동 (뒤로가기 했을때 검색 타입이 바뀌어도 검색 메뉴가 바뀌지 않는 문제 해결)
- 메타 데이터 추가
- collectionPage 에 메타데이터 추가 (공유하기 기능을 위한 Open Graph)
- 기타 수정
- 찜한장소 클릭시 라우트 /pin => /place로 수정 
- InputComponent 에서 처음 세팅되는 문자열 길이 초기화 안되는 문제 수정 (input 에 텍스트는 들어있는데 문자 길이가 0/30 이런 경우)
<br/>
- 공유하기 기능을 위한 Open-graph 를 추가하였습니다. 실제로 잘 동작하는지 확인하고, 다른 페이지들에도 적용하려고 합니다
<br/>
- #123 
<br/>
<br/>

Feat/report page #111

---

src/containers/layout/Sidebar.tsx
src/containers/layout/SidebarNotifyComponent.tsx
src/containers/notify/NotifyBox.tsx
src/containers/notify/NotifyPage.tsx
src/containers/profile/ProfileEditPage.tsx
src/containers/profile/ProfileInfoRenderer.tsx
src/hooks/useCheckIsMyMembername.tsx
src/styles/containers/main/_recommendCollectionCard.module.scss
src/styles/containers/notify/_notifyPage.module.scss
src/styles/layout/_infoListLayout.module.scss
src/styles/layout/_sidebar.module.scss
src/types/Notify.tsx
src/utils/members/fetchPostNotifications.tsx

NotifyPage
- sidebar 알림 (socket 연결)
- 알림내역 가져오기
기타
- recommendCollectionCard 의 핀list 정렬 수정
<br/>
- 소켓 연결은 배포해서 한번 확인해 봐야 합니다
<br/>
- #134 
<br/>
<br/>

Feat/report page #134

---

src/components/loading/SkeletonImage.tsx
src/containers/collection/CollectionPage.tsx
src/containers/collection/CollectionPageSkeleton.tsx
src/containers/place/PlacePage.tsx
src/containers/profile/ProfileCollectionSkeleton.tsx
src/containers/profile/ProfilePage.tsx
src/styles/components/_skeletonImage.module.scss
src/styles/containers/collection/_collectionPage.module.scss
src/styles/containers/place/_placePage.module.scss
src/styles/containers/profile/_profilePage.module.scss

- profile, collection, place 페이지 로딩 스켈레톤 추가
<br/>
- Suspense가 아닌 isLoading 사용해서 넣었는데 혹시 이상한부분 있으면 언제든 말씀해주세요
<br/>
- #70 
<br/>
<br/>

Feat/skeleton image #70

---

src/components/PinCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/layout/SidebarNotifyComponent.tsx
src/containers/pin/PinEditPage.tsx
src/containers/report/ReportPage.tsx
src/styles/containers/collection/_collectionEditPage.module.scss
src/utils/members/fetchPostNotifications.tsx

기타
- `SidebarNotifyComponent` 알림 test용 값 초기화
- 알림 목록 조회 endpoint 수정
CollectionEditPage
-  pin 수정후 collection edit page 로 되돌아 올 수 있도록 연결
-  불필요한 editbutton 삭제, edit delete button cursor pointer 로 설정
<br/>
<br/>
<br/>
<br/>

fix: SidebarNotifyComponent 알림 test용 값 초기화

---

src/utils/search/fetchDeleteSearchHistory.tsx

- 검색 기록 삭제 api endpoint 수정
<br/>
<br/>
<br/>
<br/>

fix : 검색 기록 삭제 api endpoint 수정

---

src/containers/main/MainPage.tsx
src/styles/containers/main/_mainPage.module.scss

- 메인페이지 상위 슬라이더 삭제 및 추천 컬렉션 변경
<br/>
- 컬렉션 만들고 컬렉션 번호 알려주시면 더 추가하겠습니다
- 
<br/>
- #116 
- 
<br/>
-
<br/>

Feat/main page #116

---

src/app/(default)/profile/setting/report/page.tsx
src/app/api/reports/route.tsx
src/components/PlaceCard.tsx
src/containers/layout/InfoListLayout.tsx
src/containers/main/MainPage.tsx
src/containers/profile/ProfileEditPage.tsx
src/containers/profile/ProfileSettingPage.tsx
src/containers/report/ReportDetailsPage.tsx
src/styles/containers/report/_reportPage.module.scss
src/styles/layout/_infoListLayout.module.scss

- 신고 조회 페이지 구현
- `/profile/setting/report`
- SettingPage
- 새로고침시 프로필 다시 안불러와지는 문제, profile훅 의존성배열에 넣어 해결
- 기타
- 프로필 수정페이지 tooperMsg 수정  
- infoLayout expand button 스타일 적용 안되는 문제 해결
- 미쉐린 가이드 컬렉션 id 수정
<br/>
<br/>
- #111
<br/>
<br/>

Feat/ 신고 조회 페이지 구현, Fix/새로고침시 프로필 다시 안불러와지는 문제  #111

---

src/containers/collection/CollectionPage.tsx
src/containers/search/SearchPage.tsx

- search submit시(검색 아이콘 눌러서 검색시), 쿼리스트링에 rangefilter 세팅
- 로그아웃 상태에서 컬렉션 수정 버튼 보이는 에러 수정
<br/>
<br/>
-  #145
<br/>
<br/>

fix: search submit시, 쿼리스트링에 rangefilter 세팅 #145

---

src/app/api/search/places/dummydata.json
src/containers/map/Map.tsx
src/containers/search/SearchPinRenderer.tsx
src/containers/search/SearchPlaceRenderer.tsx
src/redux/locationSlice.tsx
src/styles/containers/search/_searchPage.module.scss
src/types/Place.tsx

- 검색 결과가 마커로 띄워지도록 변경, 지도 범위 검색에 현재 보고있는 지도 영역 좌표 전달
<br/>
- 최대한 테스트는 했는데 버그가 있을 수 있습니닷 추가로 발견하면 바로 고치겠습니다
<br/>
- #145 
- #119
<br/>

Feat/지도 범위 내 검색 #145 #119

---

src/components/UserCard.tsx
src/containers/profile/FollowPage.tsx
src/containers/search/SearchPage.tsx
src/containers/search/SearchUserRenderer.tsx
src/utils/search/fetchGetSearchUser.tsx

- 유저 검색기능 추가
<br/>
- backend 배포 후 연결 확인 필요
<br/>
- #154 
<br/>
<br/>

Feat/유저 검색 기능 #154

---

src/components/PinCard.tsx
src/containers/collection/CollectionEditPage.tsx
src/containers/login/LoginPage.tsx
src/containers/notify/NotifyBox.tsx
src/styles/containers/login/_login.module.scss

회의에서 나온 이슈 일부 해결하였습니다.
-  알림 메시지 문구 통일
- PinEdit 
- collectionEditPage에서 PinEditPage로 넘어갈때, pin기존정보 넘기기
- PinCard에서 내 카드일때 신고버튼이 보이는 문제 해결 (testcode 들어가 있던 것 수정)
<br/>
<br/>
<br/>
-
<br/>

Fix/ 알림 메시지 문구 통일, PinEditPage에서 기존 핀 정보 안보이는 문제

---

src/containers/map/Map.tsx
src/containers/search/SearchPinRenderer.tsx
src/containers/search/SearchPlaceRenderer.tsx

fix: 핀 검색 결과가 마커로 띄워지도록 연결

---

src/containers/search/SearchUserRenderer.tsx
src/redux/pinEditSlice.tsx

- 유저 검색에서 로그인 유무를 확인하여, 로그인시에만 follow 버튼 보이도록 수정하였습니다
- pinEditPage 에서 가져오는 pinData가 존재하지 않을때 pinData id 값 설정 변경(기존 0 => -1 값으로)
- (commit (https://github.com/PinTogether/frontend/commit/00d896ae8170f2c618e3643d97de4601a44acfa6)
- 작업환경에서는 -1 값을 사용하면서 main 브랜치에 올리지 않아 수정커밋 추가하여 올립니다
<br/>
<br/>
<br/>
<br/>

Fix/유저 검색 follow 버튼, pinEditPage에서 사용하는 pinData 

---

src/app/(default)/layout.tsx

- google, naver에 사이트 등록하기 위한 meta tag 추가
<br/>
<br/>
- #156
<br/>
<br/>

feat: google, naver에 사이트 등록하기 위한 meta tag 추가 #156

---

src/containers/overlay/Overlay.tsx

- 로그인시 오버레이 내컬렉션, 스크랩한 컬렉션 표시 안되던 문제 수정
<br/>
- 컬렉션 정보를 받아오는 부분을 실시간으로 수정하려다 잘못된 부분이 있어서 생기던 문제였습니닷 일단 이전처럼 불러오도록 수정 했습니다
<br/>
- #177
<br/>

fix: 로그인시 오버레이 내컬렉션, 스크랩한 컬렉션 표시 안되던 문제 수정 #177
